version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - shared-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_c
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
