version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - frontend
